### ISSUE TITLE
Feature request: optional param to change case of first letter

### ISSUE THREAD

**Issue by toastyghost** [lewislbr/studlyfy#1]
Title says it all, I think. I'm super lazy and not especially familiar with TypeScript. I think it'd just be a matter of adding a second param, defaulting it to 2, only allowing it to be 1 or 2, and using that param value in the modulus conditional.

**Comment by lewislbr** [comment]
Good idea! I'll implement it 👌

**Comment by lewislbr** [comment]
Done in #2
